name: Trigger auto deployment for memo-crm-gateway

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/memo-crm-gateway-AutoDeployTrigger-7076367f-f815-4add-a5ee-e3756b466319.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MEMOCRMGATEWAY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MEMOCRMGATEWAY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MEMOCRMGATEWAY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/Dockerfilee
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.MEMOCRMGATEWAY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MEMOCRMGATEWAY_REGISTRY_PASSWORD }}
          containerAppName: memo-crm-gateway
          resourceGroup: crm-app
          imageToBuild: memoaldu/memo-crm-gateway:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


